CREATE TABLE mlb (team text primary key, eid integer, roto text, shorttrans text)
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('ARI','29','ARZ','Arizona Diamondbacks','Arizona')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('ATL','15','ATL','Atlanta Braves','Atlanta')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('BAL','1','BAL','Baltimore Orioles','Baltimore')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('BOS','2','BOS','Boston Red Sox','Boston')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('CHC','16','CHC','Chicago Cubs','Chicago Cubs')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('CIN','17','CIN','Cincinnati Reds','Cincinnati')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('CLE','5','CLE','Cleveland Indians','Cleveland')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('COL','27','COL','Colorado Rockies','Colorado')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('CWS','4','CWS','Chicago White Sox','Chicago Sox')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('DET','6','DET','Detroit Tigers','Detroit')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('HOU','18','HOU','Houston Astros','Houston')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('KC','7','KC','Kansas City Royals','Kansas City')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('LAA','3','ANA','Los Angeles Angels','LA Angels')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('LAD','19','LA','Los Angeles Dodgers','LA Dodgers')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('MIA','28','FLA','Miami Marlins','Miami')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('MIL','8','MLW','Milwaukee Brewers','Milwaukee')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('MIN','9','MIN','Minnesota Twins','Minnesota')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('NYM','21','NYM','New York Mets','NY Mets')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('NYY','10','NYY','New York Mets','NY Yankees')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('OAK','11','OAK','Oakland Athletics','Oakland')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('PHI','22','PHI','Philadelphia Phillies','Philadelphia')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('PIT','23','PIT','Pittsburgh Pirates','Pittsburgh')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('SD','25','SD','San Diego Padres','San Diego')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('SEA','12','SEA','Seattle Mariners','Seattle')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('SF','26','SF','San Francisco Giants','San Francisco')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('STL','24','STL','St. Louis Cardinals','St. Louis')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('TB','30','TB','Tampa Bay Rays','Tampa Bay')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('TEX','13','TEX','Texas Rangers','Texas')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('TOR','14','TOR','Toronto Blue Jays','Toronto')
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans) values ('WSH','20','WAS','Washington Nationals','Washington')
