CREATE TABLE mlb (team text primary key, eid integer, roto text, fulltrans text, shorttrans text, yahoo text);
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('ARI','29','ARZ','Arizona Diamondbacks','Arizona','ari');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('ATL','15','ATL','Atlanta Braves','Atlanta','atl');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('BAL','1','BAL','Baltimore Orioles','Baltimore','bal');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('BOS','2','BOS','Boston Red Sox','Boston','bos');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('CHC','16','CHC','Chicago Cubs','Chicago Cubs','chc');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('CIN','17','CIN','Cincinnati Reds','Cincinnati','cin');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('CLE','5','CLE','Cleveland Indians','Cleveland','cle');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('COL','27','COL','Colorado Rockies','Colorado','col');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('CWS','4','CWS','Chicago White Sox','Chicago Sox','chw');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('DET','6','DET','Detroit Tigers','Detroit','det');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('HOU','18','HOU','Houston Astros','Houston','hou');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('KC','7','KC','Kansas City Royals','Kansas City','kan');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('LAA','3','ANA','Los Angeles Angels','LA Angels','laa');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('LAD','19','LA','Los Angeles Dodgers','LA Dodgers','lad');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('MIA','28','FLA','Miami Marlins','Miami','mia');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('MIL','8','MLW','Milwaukee Brewers','Milwaukee','mil');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('MIN','9','MIN','Minnesota Twins','Minnesota','min');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('NYM','21','NYM','New York Mets','NY Mets','nym');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('NYY','10','NYY','New York Yankees','NY Yankees','nyy');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('OAK','11','OAK','Oakland Athletics','Oakland','oak');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('PHI','22','PHI','Philadelphia Phillies','Philadelphia','phi');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('PIT','23','PIT','Pittsburgh Pirates','Pittsburgh','pit');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('SD','25','SD','San Diego Padres','San Diego','sdg');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('SEA','12','SEA','Seattle Mariners','Seattle','sea');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('SF','26','SF','San Francisco Giants','San Francisco','sfo');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('STL','24','STL','St. Louis Cardinals','St. Louis','stl');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('TB','30','TB','Tampa Bay Rays','Tampa Bay','tam');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('TEX','13','TEX','Texas Rangers','Texas','tex');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('TOR','14','TOR','Toronto Blue Jays','Toronto','tor');
INSERT INTO mlb (team,eid,roto,fulltrans,shorttrans, yahoo) values ('WSH','20','WAS','Washington Nationals','Washington','was');
