CREATE TABLE mlb (team text primary key, eid integer, roto text, fulltrans text, ename text, short text, yahoo text, eshort text);
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('ARI','29','ARZ','Arizona Diamondbacks','Arizona','diamondbacks','ari','ari');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('ATL','15','ATL','Atlanta Braves','Atlanta','braves','atl','atl');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('BAL','1','BAL','Baltimore Orioles','Baltimore','orioles','bal','bal');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('BOS','2','BOS','Boston Red Sox','Boston','redsox','bos','bos');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('CHC','16','CHC','Chicago Cubs','Chicago Cubs','cubs','chc','chc');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('CIN','17','CIN','Cincinnati Reds','Cincinnati','reds','cin','cin');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('CLE','5','CLE','Cleveland Indians','Cleveland','indians','cle','cle');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('COL','27','COL','Colorado Rockies','Colorado','rockies','col','col');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('CWS','4','CWS','Chicago White Sox','Chicago Sox','whitesox','chw','chw');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('DET','6','DET','Detroit Tigers','Detroit','tigers','det','det');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('HOU','18','HOU','Houston Astros','Houston','astros','hou','hou');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('KC','7','KC','Kansas City Royals','Kansas City','royals','kan','kc');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('LAA','3','ANA','Los Angeles Angels','LA Angels','angels','laa','laa');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('LAD','19','LA','Los Angeles Dodgers','LA Dodgers','dodgers','lad','lad');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('MIA','28','FLA','Miami Marlins','Miami','Miami','mia','mia');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('MIL','8','MLW','Milwaukee Brewers','Milwaukee','brewers','mil','mil');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('MIN','9','MIN','Minnesota Twins','Minnesota','twins','min','min');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('NYM','21','NYM','New York Mets','NY Mets','mets','nym','nym');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('NYY','10','NYY','New York Yankees','NY Yankees','yankees','nyy','nyy');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('OAK','11','OAK','Oakland Athletics','Oakland','athletics','oak','oak');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('PHI','22','PHI','Philadelphia Phillies','Philadelphia','phillies','phi','phi');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('PIT','23','PIT','Pittsburgh Pirates','Pittsburgh','pirates','pit','pit');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('SD','25','SD','San Diego Padres','San Diego','padres','sdg','sd');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('SEA','12','SEA','Seattle Mariners','Seattle','mariners','sea','sea');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('SF','26','SF','San Francisco Giants','San Francisco','giants','sfo','sf');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('STL','24','STL','St. Louis Cardinals','St. Louis','cardinals','stl','stl');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('TB','30','TB','Tampa Bay Rays','Tampa Bay','rays','tam','tb');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('TEX','13','TEX','Texas Rangers','Texas','rangers','tex','tex');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('TOR','14','TOR','Toronto Blue Jays','Toronto','bluejays','tor','tor');
INSERT INTO mlb (team,eid,roto,fulltrans,ename,short,yahoo,eshort) values ('WSH','20','WAS','Washington Nationals','Washington','nationals','was','wsh');
